# -*- coding: utf-8 -*-
"""CruiseShip.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I5uLyttf3smORC1cQNfn1fFPXGS1acEy

To read the file and display columns, you can use the pandas library.
"""

import pandas as pd

df = pd.read_csv('cruise_ship_info.csv')
print(df.columns)

"""Calculating basic statistics of the data"""

print(df.describe())

"""Selecting columns that will be probably important to predict “crew” size"""

cols_to_use = ['Age', 'Tonnage', 'passengers', 'length', 'cabins', 'passenger_density', 'crew']
df = df[cols_to_use]

"""Creating training and testing sets"""

from sklearn.model_selection import train_test_split

train_set, test_set = train_test_split(df, test_size=0.4, random_state=42)

"""Building a machine learning model to predict the ‘crew’ size"""

from sklearn.linear_model import LinearRegression

X_train = train_set.drop('crew', axis=1)
y_train = train_set['crew'].values

X_test = test_set.drop('crew', axis=1)
y_test = test_set['crew'].values

lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)

"""Calculating the Pearson correlation coefficient for the training set and testing data sets"""

import numpy as np
from scipy.stats import pearsonr

y_train_pred = lin_reg.predict(X_train)
corr_train, _ = pearsonr(y_train, y_train_pred)

y_test_pred = lin_reg.predict(X_test)
corr_test, _ = pearsonr(y_test, y_test_pred)

print('Pearson correlation (training set):', corr_train)
print('Pearson correlation (testing set):', corr_test)